apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-project
  labels:
    app: argocd
spec:
  description: Our ArgoCD Project to deploy our app locally
  sourceRepos:
  - "https://github.com/clemcheyrou/*"
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false

--

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd
  name: argocd-app
spec:
  project: argocd-project
  source:
    repoURL: https://github.com/clemcheyrou/Inception-of-things.git
    path: p3/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true