apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd
  name: argocd-app
spec:
  project: default
  source:
    repoURL: https://github.com/clemcheyrou/Inception-of-things.git
    path: p3/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true