---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil42
spec:
  rules:
  - host: wil42.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wil42
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wil42
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  wil42

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-nginx
spec:
  selector:
    matchLabels:
      app: wil42
  template:
    metadata:
      labels:
        app: wil42
    spec:
      containers:
      - name: wil42
        image: wil42/playground
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: wil42
          mountPath: /
      volumes:
      - name: wil42