apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd
  name: argocd-app
spec:
  project: argocd-project
  source:
    repoURL: https://github.com/albibou/ccheyrou-app.git
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
