apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    name: gitlab
spec:
  type: LoadBalancer
  selector:
    name: gitlab
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 1022
      targetPort: ssh

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        name: gitlab
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: |
                external_url 'http://localhost/gitlab'
                gitlab_rails['gitlab_relative_url_root'] = "/gitlab"
        # env:
        # - name: GITLAB_ROOT_PASSWORD
        #   value: root

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  rules:
  - host: git.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port: 
              number: 80
  - host: git-ssh.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port: 
              number: 1022

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-nodeport
  namespace: gitlab
  labels:
    name: gitlab
spec:
  type: NodePort
  selector:
    name: gitlab
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
    - name: http
      port: 80
      targetPort: http
