Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  user = ENV['USER']
  machine_1 = "#{user}S"
  machine_2 = "#{user}SW"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1 
    vb.memory = "512"
  end

  config.vm.define 'ccheyrouS' do |machine|
    machine.vm.hostname = 'ccheyrouS'
    machine.vm.network "private_network", ip: "192.168.56.110", hostname: true

  end

  config.vm.define 'ccheyrouSW' do |machine|
    machine.vm.hostname = 'ccheyrouSW'
    machine.vm.network "private_network", ip: "192.168.56.111", hostname: true
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: "cat /home/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
end
