global:
  edition: ce
  hosts:
    domain: local
    externalIP: 127.0.0.1
    ssh: ~
    gitlab:
      name: gitlab.xip.io 
      https: true
    registry:
      name: gitlab-registry.xip.io
      https: true
    minio:
      name: gitlab-minio.xip.io
      https: true
  minio:
    enabled: true
  ingress:
    configureCertmanager: false
    class: "nginx"
    enabled: true
    tls:
      enabled: true
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: true
redis:
  install: true
postgresql:
  install: true
gitlab-runner:
  install: true
registry:
  enable: true