---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  labels:
    app: dev
spec:
  rules:
  - http:
      paths:
      - path: /p3/dev
        pathType: Prefix
        backend:
          service:
            name: dev-service
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dev-service
  labels:
    app: dev
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dev-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: dev-volume
        configMap:
          name: app-html