---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  labels:
    app: dev
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dev-service
  labels:
    app: dev
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: wil42
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dev-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: dev-volume
        configMap:
          name: app-html
--
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-html
  labels:
    app: dev
data:
  index.html: |
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
    <html lang="en">
      <head>
          <meta http-equiv="content-type" content="text/html; charset=utf-8">
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
          <title>ArgoCD Rocks</title>
          <style type="text/css">
            body { text-align: center; margin: 80px 0px 0px 0px; font-family: 'Roboto', sans-serif; }
            h1 { font-size: 6em; }
          </style>
      </head>
      <body>
        <div>
          <img height="400px" src="https://branding.cncf.io/img/projects/argo/icon/color/argo-icon-color.svg"></svg>
          <h1>ArgoCD Rocks !</h1>
          <p>Version 1.2</p>
        </div>
      </body>
    </html>